### PR TITLE
Fix: Linux Exec apppath should be in quotes, it may contains spaces

### PR DESCRIPTION
**Pull request by brendtumi**
- Target platforms this affects (Linux, Mac, Mac app store, and or Windows): Linux
- What problem does this solve? Wraping appPath with quotes
- Could it break any existing functionality for users? No

### CODE REVIEW

**Comment by vadim-ch** [comment]
Oh, it's a big problem. Please merge pull request. Now I am forced to do dirty hack to override `appPath`.

**Comment by brendtumi** [comment]
@vadim-ch you may use my fork repository until merge happen.

**Comment by sidneys** [comment]
@vadim-ch @brendtumi 
Thanks for the heads-up, this is a major bug and does not throw any errors. I am using the fork for the time being also.

@teamwork-bot 
Please merge this asap

**Comment by sidneys** [comment]
Note: This PR does not fix the issue, as it includes the ´´´hiddenArg´ inside the quotes. I created a new PR addressing this issue.

**Comment by adam-lynch** [comment]
Thanks but closing in favour of #57

**Comment by adam-lynch** [comment]
Thanks but closing in favour of #57

**Pull request closed without merging**
