### PR TITLE
Add microsoft store support

### PR DESCRIPTION
**Pull request by miguelx97**
## Support for Microsoft Store

- Target platform: Appx app downloaded from Microsoft Store
- What problem does this solve? This feature allows to auto launch Microsoft Store appx apps at startup.
- Could it break any existing functionality for users? No

Example: `new autoLaunch({  name: 'APP_NAME', path:"DEV_ID.APP_ID!PACKAGE_NAME", isHidden: true })`

### CODE REVIEW

**Comment by hovancik** [comment]
@miguelx97 any chance you published this as package somewhere?

**Comment by Oxalin** [comment]
Since I don't think @miguelx97 is still around to make the changes, I'm pulling in this PR and I'll fix the details afterward.

**Review by Oxalin — APPROVED** [review]
Since I don't think the miguelx97 is still around to make the requested adjustments, I'm pulling in this PR and I'll make the little requested changes afterward.

**Comment by hovancik** [comment]
@Oxalin how would I ago with debugging this feature? I am trying with my app but doesn't seem to work, as in: app is not started after reboot. 

```
      const autoLaunch = require('auto-launch')
      const stretchlyLauncher = new autoLaunch({ name: 'Stretchly', path:"33881JanHovancik.stretchly_24fg4m0zq65je!Stretchly", isHidden: true })
      if (value) {
        stretchlyLauncher.enable()
      } else {
        stretchlyLauncher.disable()
      }
```

Can I check some Window's location or something? I am on Windows 11.

**Comment by Oxalin** [comment]
Hi. Sorry for the late comment. I've been missing time for my implication on side projectst.

First, you would have to check in the registry if a value is added on enable() under HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

Do you get anything?

**Comment by Oxalin** [comment]
We woud need to check if there is an error with this scenario then. I'll see what I come with if you are willing to test it.

Note to myself : add a test case to validate if it works as intended.

**Comment by Oxalin** [comment]
I'm opening issue 122

**Pull request merged**
