### PR TITLE
Add ghactions support

### PR DESCRIPTION
**Pull request by 4ver**
- Target platforms this affects (Linux, Mac, Mac app store, and or Windows): 
- What problem does this solve?
- Could it break any existing functionality for users?

---

### CODE REVIEW

**Comment by Oxalin** [comment]
"coffee-script" module must be updated to "coffeescript" (it was renamed) with recent versions. This should allow to run test with Node.js 8 and 14.

However, for Node.js 4, I see this that probably needs to be fixed or telling us we shouldn't support Node.js 4: npm WARN engine temp@0.8.4: wanted: {"node":">=6.0.0"} (current: {"node":"4.9.1","npm":"2.15.11"})

**Review by Oxalin — DISMISSED** [review]

**Comment by Oxalin** [comment]
Also, I would suggest to test against LTS releases that are still supported or the ones that were last pushed out of maintenance. This means 16, 18 and 20.

**Comment by Oxalin** [comment]
gulp-coffeelint has not been updated for the last 8 years and still depends on "coffee-script" (with a "-")...

**Comment by Oxalin** [comment]
Also, for Node >= 10, we need to move to gulp 4 (that is why I had the "natives" modules in my commit series because it was a workaround that some people had identified) and update whatever needs to be updated.

**Comment by Oxalin** [comment]
We seem to have a problem under macOS where the CI testing fails to .enable() autolaunch Calculator, and thus fails to disable it. Was it passing before?

**Review by Oxalin — APPROVED** [review]
Looks good and tested. Works on Linux and Windows.

I'm worried about the macOS tests failing, but it seems to have nothing to do with the changes in this PR.

**Comment by 4ver** [comment]
> We seem to have a problem under macOS where the CI testing fails to .enable() autolaunch Calculator, and thus fails to disable it. Was it passing before?

This was working on older versions of macos afaik. In more recent versions only the Launch Agent way works.

**Comment by 4ver** [comment]
Not sure it was a good idea to merge this as the tests aren't passing 😅

**Comment by Oxalin** [comment]
> Not sure it was a good idea to merge this as the tests aren't passing 😅

I though it was already failing prior to your PR. My bad. I'll review your new PR.

**Pull request merged**
