### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by willbarrett**
Fixes https://github.com/Teamwork/node-auto-launch/issues/3
Fixes https://github.com/sindresorhus/module-requests/issues/17

### CODE REVIEW

**Comment by 4ver** [comment]
Brilliant! I'll give this a test tomorrow.

Thanks @willbarrett :dancer:

**Comment by willbarrett** [comment]
My pleasure - we needed this for Speak :)

**Comment by willbarrett** [comment]
Hey @4ver - have you given this a blast? Any feedback?

**Comment by adam-lynch** [comment]
@willbarrett thanks a million for this. I'm not sure what's the best way to test this?

**Comment by adam-lynch** [comment]
As @4ver just suggested to me, maybe we could bundle in linux and windows executables and use though in the (simple) test we have already. I could create a simple NW.js ask in the meantime which uses this module and try it on someone's machine / in a VM.

**Comment by adam-lynch** [comment]
Closing in favour of #10

**Comment by adam-lynch** [comment]
Hey @willbarrett, what's the deal with support for this? Do you know which distros aren't supported, etc?

**Comment by willbarrett** [comment]
Hey @adam-lynch - I'm not 100% sure about which distros aren't supported - this should work for most debian and fedora based distros. If you're getting reports for a specific one, let me know and I'll be happy to debug it in a VM.

**Comment by adam-lynch** [comment]
@willbarrett no reports. Just thinking it would make sense to stick it in the readme or something. We don't use this yet ourselves in production but it would be good to know I guess.

**Comment by willbarrett** [comment]
@adam-lynch makes sense. You mentioned on another ticket that you have a small sample app that uses this code. Is it on GH anywhere? I have a few VMs I could give it a whirl with, so you could at least say "tested with x, y, z distributions".

**Comment by willbarrett** [comment]
@adam-lynch makes sense. You mentioned on another ticket that you have a small sample app that uses this code. Is it on GH anywhere? I have a few VMs I could give it a whirl with, so you could at least say "tested with x, y, z distributions".

**Comment by adam-lynch** [comment]
@willbarrett oh yeah that, it's here https://github.com/adam-lynch/node-auto-launch-test-app (really rough). Sounds good.

**Comment by willbarrett** [comment]
@adam-lynch thanks. I'll try to get back to you by Monday with the results.

**Comment by adam-lynch** [comment]
@willbarrett :+1:

**Comment by adam-lynch** [comment]
From the [Desktop Entry Specification](http://standards.freedesktop.org/desktop-entry-spec/latest/index.html#introduction):

>Both the KDE and GNOME desktop environments have adopted a similar format for "desktop entries", or configuration files describing how a particular program is to be launched, how it appears in menus, etc. It is to the larger community's benefit that a unified standard be agreed upon by all parties such that interoperation between the two environments, and indeed any additional environments that implement the specification, becomes simpler.

@willbarrett does that confirm what you said? Or mean more support than you said? :smile:

**Comment by willbarrett** [comment]
Hi @adam-lynch - Yup, this supports what I said. Most distributions use either KDE or Gnome for the window manager. Sorry this fell off my plate - I've been travelling for the holidays, but I'm back now. I'll pick up the investigation in the AM.

**Comment by adam-lynch** [comment]
@willbarrett no problem, thanks. I'm just writing something on this module and checked the docs :smile:

**Pull request closed without merging**
